name: Run Floorsheet Script

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "20 9 * * 0-4"  # 3:05 PM NPT (9:20 AM UTC) Sunday to Thursday

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run floorsheet_github.py
      run: python floorsheet_github.py
